version: '3'

services:
  app:
    image: faasjs/vscode
    command: sleep infinity
    tty: true
    environment:
      SECRET_KNEX_CONNECTION: postgresql://development@pg/development
    volumes:
      - ..:/root/app:delegated

      - /root/app/node_modules

      - /root/app/packages/api/node_modules
      - /root/app/packages/api/tmp

      - /root/app/packages/www/node_modules

      - ~/.npmrc:/root/.npmrc:delegated
      - ~/.ssh:/root/.ssh:delegated
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - pg
      - pg_testing1
  pg:
    image: postgres:alpine
    environment:
      POSTGRES_USER: development
      POSTGRES_DB: development
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ../packages/api/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
  pg_testing1:
    image: postgres:alpine
    environment:
      POSTGRES_DB: testing
      POSTGRES_USER: testing
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ../packages/api/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
